### ISSUE TITLE
Error in v 1.7.3.1

### ISSUE THREAD

**Issue by denisenkom** [denisenkom/pytds#37]
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/pierovbg/workspace/crm-actors/actors/presentation/cli/management/commands/convert_profiles.py", line 18, in handle
    get_external_updates_processor().process_external_updates(converter)
  File "/home/pierovbg/workspace/crm-actors/actors/domain/external_updates/processor.py", line 29, in process_external_updates
    new_updates = self._repository.get_updates_after(last_processed)
  File "/home/pierovbg/workspace/crm-actors/actors/persistence/external_updates/update_repository.py", line 57, in get_updates_after
    return map(ExternalAccountUpdateDescription.fill_from_object, updates)
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/django/db/models/query.py", line 141, in __iter__
    self._fetch_all()
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/django/db/models/sql/compiler.py", line 1156, in cursor_iter
    sentinel):
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/django/db/models/sql/compiler.py", line 1155, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(GET_ITERATOR_CHUNK_SIZE)),
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/django/db/utils.py", line 101, in inner
    return func(*args, **kwargs)
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/pytds/__init__.py", line 749, in fetchmany
    row = self.fetchone()
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/pytds/__init__.py", line 734, in fetchone
    row = self._session.fetchone()
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/pytds/tds.py", line 3428, in fetchone
    if not self.next_row():
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/pytds/tds.py", line 3439, in next_row
    self.process_token(marker)
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/pytds/tds.py", line 3390, in process_token
    return handler(self)
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/pytds/tds.py", line 3500, in <lambda>
    TDS_ROW_TOKEN: lambda self: self.process_row(),
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/pytds/tds.py", line 2595, in process_row
    curcol.value = self.row[i] = curcol.type.read(r)
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/pytds/tds.py", line 929, in read
    return r.get_int()
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/pytds/tds.py", line 623, in get_int
    return self.unpack(_int_le)[0]
  File "/home/pierovbg/.venvs/actors/lib/python3.3/site-packages/pytds/tds.py", line 611, in unpack
    return struct.unpack_from(buf, offset)
struct.error: unpack_from requires a buffer of at least 4 bytes
```

**Comment by bradleyy** [comment]
I'm running into something quite similar, just with a slightly different code path to the unpack_from failure.

Any hints on what might be causing this, or workarounds?

**Comment by denisenkom** [comment]
Can you reproduce this problem?

**Comment by bradleyy** [comment]
I can definitely reproduce; a certain set of queries over certain (large-ish) datasets will reliably cause it.

**Comment by bradleyy** [comment]
Slightly edited for clarity and privacy. Shows the error; this same code works fine on most datasets (I have a lot of similar databases), but I get this consistently on some of the datasets. It seems to be related to size, but not sure if it is related or causative.

File "<proj directory>/lib/python2.7/site-packages/django/db/utils.py", line 101, in inner
    return func(*args, **kwargs)
  File "<proj directory>/lib/python2.7/site-packages/pytds/__init__.py", line 749, in fetchmany
    row = self.fetchone()
  File "<proj directory>/lib/python2.7/site-packages/pytds/__init__.py", line 734, in fetchone
    row = self._session.fetchone()
  File "<proj directory>/lib/python2.7/site-packages/pytds/tds.py", line 3428, in fetchone
    if not self.next_row():
  File "<proj directory>/lib/python2.7/site-packages/pytds/tds.py", line 3439, in next_row
    self.process_token(marker)
  File "<proj directory>/lib/python2.7/site-packages/pytds/tds.py", line 3390, in process_token
    return handler(self)
  File "<proj directory>/lib/python2.7/site-packages/pytds/tds.py", line 3500, in <lambda>
    TDS_ROW_TOKEN: lambda self: self.process_row(),
  File "<proj directory>/lib/python2.7/site-packages/pytds/tds.py", line 2595, in process_row
    curcol.value = self.row[i] = curcol.type.read(r)
  File "<proj directory>/lib/python2.7/site-packages/pytds/tds.py", line 1771, in read
    return self._subtype.read(r)
  File "<proj directory>/lib/python2.7/site-packages/pytds/tds.py", line 1704, in read
    days, t = r.unpack(self._struct)
  File "<proj directory>/lib/python2.7/site-packages/pytds/tds.py", line 611, in unpack
    return struct.unpack_from(buf, offset)
error: unpack_from requires a buffer of at least 8 bytes

**Comment by bradleyy** [comment]
Further update: this seems to actually be related to a timeout. I did a gruesome hack, doing the equivalent of socket.settimeout(900) on every read (since this was just meant to be a quick test). This "fixed" the issue above.

**Comment by denisenkom** [comment]
Is it failing in a middle of a recordset, or at the very beginning?

**Comment by bradleyy** [comment]
It was failing in the middle; but after changing the socket timeout to a much longer value (the DB in question is physically distant, and some of the queries are large) fixed the issue for me.

**Comment by bradleyy** [comment]
Still getting this. Don't seem to have a reliable repro; I'm still thinking it's related to a timeout.

**Comment by jmartinez-jobsity** [comment]
Is there any update about this issue? It's causing me issues when getting big amounts of data

**Comment by denisenkom** [comment]
@jmartinez-jobsity did you use latest version?  Can you upload stack trace?

**Comment by jmartinez-jobsity** [comment]
```
2016-10-19T19:16:48.179302720Z     for row in cursor:
2016-10-19T19:16:48.179306288Z   File "/usr/lib/python3.5/site-packages/pytds/__init__.py", line 771, in __next__
2016-10-19T19:16:48.179309526Z     row = self.fetchone()
2016-10-19T19:16:48.179312637Z   File "/usr/lib/python3.5/site-packages/pytds/__init__.py", line 744, in fetchone
2016-10-19T19:16:48.179316125Z     row = self._session.fetchone()
2016-10-19T19:16:48.179330767Z   File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 3780, in fetchone
2016-10-19T19:16:48.179335058Z     if not self.next_row():
2016-10-19T19:16:48.179338376Z   File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 3791, in next_row
2016-10-19T19:16:48.179341718Z     self.process_token(marker)
2016-10-19T19:16:48.179344982Z   File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 3739, in process_token
2016-10-19T19:16:48.179348327Z     return handler(self)
2016-10-19T19:16:48.179351599Z   File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 3857, in <lambda>
2016-10-19T19:16:48.179355376Z     TDS_ROW_TOKEN: lambda self: self.process_row(),
2016-10-19T19:16:48.179358471Z   File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 2832, in process_row
2016-10-19T19:16:48.179361688Z     curcol.value = self.row[i] = curcol.type.read(r)
2016-10-19T19:16:48.179385566Z   File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 1207, in read
2016-10-19T19:16:48.179390126Z     return self.subtypes[size].read(r)
2016-10-19T19:16:48.179393148Z   File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 1270, in read
2016-10-19T19:16:48.179396389Z     return r.get_int()
2016-10-19T19:16:48.179399388Z   File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 799, in get_int
2016-10-19T19:16:48.179402599Z     return self.unpack(_int_le)[0]
2016-10-19T19:16:48.179405683Z   File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 783, in unpack
2016-10-19T19:16:48.179408987Z     return struct.unpack_from(buf, offset)
2016-10-19T19:16:48.179412223Z struct.error: unpack_from requires a buffer of at least 4 bytes```

**Comment by denisenkom** [comment]
Try latest version from master branch.  It has a change that enabled TCP keep alive which should resolve issue with connection timeout.

**Comment by jmartinez-jobsity** [comment]
Still an issue in the last version (1.8.2):

```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "<stdin>", line 4, in <listcomp>
  File "/usr/lib/python3.5/site-packages/pytds/__init__.py", line 771, in __next__
    row = self.fetchone()
  File "/usr/lib/python3.5/site-packages/pytds/__init__.py", line 744, in fetchone
    row = self._session.fetchone()
  File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 3780, in fetchone
    if not self.next_row():
  File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 3791, in next_row
    self.process_token(marker)
  File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 3739, in process_token
    return handler(self)
  File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 3857, in <lambda>
    TDS_ROW_TOKEN: lambda self: self.process_row(),
  File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 2832, in process_row
    curcol.value = self.row[i] = curcol.type.read(r)
  File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 1207, in read
    return self.subtypes[size].read(r)
  File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 2356, in read
    hi, lo = r.unpack(self._struct)
  File "/usr/lib/python3.5/site-packages/pytds/tds.py", line 783, in unpack
    return struct.unpack_from(buf, offset)
struct.error: unpack_from requires a buffer of at least 8 bytes
```

**Comment by denisenkom** [comment]
You should use latest from master branch, not from pypi

**Comment by jmartinez-jobsity** [comment]
I cannot use the master branch atm, our current setup and data storage won't let me set the conditions under which the bug raises. Let me know when it gets to pypi so I can give it a try. Thanks

**Comment by denisenkom** [comment]
Can somebody else verify this fix?

**Comment by jmartinez-jobsity** [comment]
This should be reopened as it is still present on the top of the master branch:
```File "/app/pytds/__init__.py", line 793, in __next__
    row = self.fetchone()
  File "/app/pytds/__init__.py", line 766, in fetchone
    row = self._session.fetchone()
  File "/app/pytds/tds.py", line 1586, in fetchone
    if not self.next_row():
  File "/app/pytds/tds.py", line 1597, in next_row
    self.process_token(marker)
  File "/app/pytds/tds.py", line 1545, in process_token
    return handler(self)
  File "/app/pytds/tds.py", line 1663, in <lambda>
    tds_base.TDS_ROW_TOKEN: lambda self: self.process_row(),
  File "/app/pytds/tds.py", line 711, in process_row
    curcol.value = self.row[i] = curcol.serializer.read(r)
  File "/app/pytds/tds_types.py", line 394, in read
    return self.subtypes[size].read(r)
  File "/app/pytds/tds_types.py", line 1255, in read
    days, t = r.unpack(self._struct)
  File "/app/pytds/tds.py", line 167, in unpack
    return struc.unpack_from(buf, offset)
struct.error: unpack_from requires a buffer of at least 8 bytes```

**Comment by bylsmad** [comment]
I am also able to reproduce this bug with master branch downloaded last week

**Comment by nichcz** [comment]
+1 facing same error on actual latest version 1.8.2

```
  File "/home/petr/olc/python/django/metrum/virtual/local/lib/python2.7/site-packages/django/db/models/query.py", line 62, in __iter__
    for row in compiler.results_iter(results):
  File "/home/petr/olc/python/django/metrum/virtual/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 831, in results_iter
    for rows in results:
  File "/home/petr/olc/python/django/metrum/virtual/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1276, in cursor_iter
    sentinel):
  File "/home/petr/olc/python/django/metrum/virtual/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1275, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(GET_ITERATOR_CHUNK_SIZE)),
  File "/home/petr/olc/python/django/metrum/virtual/local/lib/python2.7/site-packages/django/db/utils.py", line 101, in inner
    return func(*args, **kwargs)
  File "/home/petr/olc/python/django/metrum/virtual/local/lib/python2.7/site-packages/pytds/__init__.py", line 759, in fetchmany
    row = self.fetchone()
  File "/home/petr/olc/python/django/metrum/virtual/local/lib/python2.7/site-packages/pytds/__init__.py", line 744, in fetchone
    row = self._session.fetchone()
  File "/home/petr/olc/python/django/metrum/virtual/local/lib/python2.7/site-packages/pytds/tds.py", line 3780, in fetchone
    if not self.next_row():
  File "/home/petr/olc/python/django/metrum/virtual/local/lib/python2.7/site-packages/pytds/tds.py", line 3791, in next_row
    self.process_token(marker)
  File "/home/petr/olc/python/django/metrum/virtual/local/lib/python2.7/site-packages/pytds/tds.py", line 3739, in process_token
    return handler(self)
  File "/home/petr/olc/python/django/metrum/virtual/local/lib/python2.7/site-packages/pytds/tds.py", line 3858, in <lambda>
    TDS_NBC_ROW_TOKEN: lambda self: self.process_nbcrow(),
  File "/home/petr/olc/python/django/metrum/virtual/local/lib/python2.7/site-packages/pytds/tds.py", line 2855, in process_nbcrow
    value = curcol.type.read(r)
  File "/home/petr/olc/python/django/metrum/virtual/local/lib/python2.7/site-packages/pytds/tds.py", line 1207, in read
    return self.subtypes[size].read(r)
  File "/home/petr/olc/python/django/metrum/virtual/local/lib/python2.7/site-packages/pytds/tds.py", line 1270, in read
    return r.get_int()
  File "/home/petr/olc/python/django/metrum/virtual/local/lib/python2.7/site-packages/pytds/tds.py", line 799, in get_int
    return self.unpack(_int_le)[0]
  File "/home/petr/olc/python/django/metrum/virtual/local/lib/python2.7/site-packages/pytds/tds.py", line 783, in unpack
    return struct.unpack_from(buf, offset)
error: unpack_from requires a buffer of at least 4 bytes
```
