### ISSUE TITLE
pytds fails on string decode (wrong server encoding detection?)

### ISSUE THREAD

**Issue by Ashald** [denisenkom/pytds#50]
While the MS SQL Server DB's collation is `Latin1_General_BIN` pytds is trying to use `cp1252` collation for decoding which doesn't seem right to me.

Other possible cause is so-known [Double Mis-Encoding] (http://www.i18nqa.com/debug/bug-double-conversion.html), which, I guess would be nice to handle to by using either `ignore` or `replace` error schema for decoding.

```
Traceback (most recent call last):
  ...
  File "/usr/lib/python3.4/site-packages/pytds/__init__.py", line 761, in __next__
    row = self.fetchone()
  File "/usr/lib/python3.4/site-packages/pytds/__init__.py", line 734, in fetchone
    row = self._session.fetchone()
  File "/usr/lib/python3.4/site-packages/pytds/tds.py", line 3428, in fetchone
    if not self.next_row():
  File "/usr/lib/python3.4/site-packages/pytds/tds.py", line 3439, in next_row
    self.process_token(marker)
  File "/usr/lib/python3.4/site-packages/pytds/tds.py", line 3390, in process_token
    return handler(self)
  File "/usr/lib/python3.4/site-packages/pytds/tds.py", line 3500, in <lambda>
    TDS_ROW_TOKEN: lambda self: self.process_row(),
  File "/usr/lib/python3.4/site-packages/pytds/tds.py", line 2595, in process_row
    curcol.value = self.row[i] = curcol.type.read(r)
  File "/usr/lib/python3.4/site-packages/pytds/tds.py", line 1143, in read
    return r.read_str(size, self._codec)
  File "/usr/lib/python3.4/site-packages/pytds/tds.py", line 642, in read_str
    return codec.decode(readall(self, size))[0]
  File "/usr/lib/python3.4/encodings/cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 5: character maps to <undefined>
```

**Comment by denisenkom** [comment]
8D doesn't present in both Latin1 (https://en.wikipedia.org/wiki/ISO/IEC_8859-1) and cp1252 (https://en.wikipedia.org/wiki/Windows-1252), so the problem is probably with the data in the table.

**Comment by slarrain** [comment]
What would the solution to this problem be? (Besides fixing the data on the table).

**Comment by denisenkom** [comment]
First you would need to figure out the actual encoding.  Once you know the encoding you would have a number of options.  One option is to read data as varbinary and then decode it using correct encoding.
